// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://futewqpwbrhjfybzrlgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1dGV3cXB3YnJoamZ5YnpybGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDc2MTYsImV4cCI6MjA2MDUyMzYxNn0.05EUjSlMAe3QGwbYeoFZBxnquSqz3eSs2KowxpvjaHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);